import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Heart, Users, Target, Shield } from "lucide-react";
import PageNavigation from "@/components/PageNavigation";

const About = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20 py-12">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent">
              About Sarvadamana
            </h1>
            <p className="text-lg text-muted-foreground">
              Your trusted companion in mental wellness and emotional well-being
            </p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="w-6 h-6 text-primary" />
                Our Mission
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-foreground/80">
                Sarvadamana is dedicated to making mental health support accessible, 
                personalized, and effective for everyone. We believe that mental wellness 
                is a journey, and we're here to support you every step of the way.
              </p>
              <p className="text-foreground/80">
                Our platform combines evidence-based therapeutic techniques with modern 
                technology to provide you with tools, resources, and support tailored to 
                your unique needs.
              </p>
            </CardContent>
          </Card>

          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Users className="w-5 h-5 text-primary" />
                  Community
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground/80">
                  Join a supportive community where you can share experiences and 
                  grow together in your wellness journey.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Target className="w-5 h-5 text-primary" />
                  Personalized
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground/80">
                  Get customized wellness plans and resources based on your specific 
                  needs, goals, and preferences.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Shield className="w-5 h-5 text-primary" />
                  Confidential
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground/80">
                  Your privacy and security are our top priorities. All your data 
                  is encrypted and handled with utmost care.
                </p>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>What We Offer</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">Personalized wellness plans generated by AI</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">Daily mood tracking and insights</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">CBT-based therapeutic support</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">Mindfulness and meditation resources</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">24/7 AI-powered mental health support</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="text-foreground/80">Specialized programs for students, employees, women, and elderly</span>
                </li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>
      <PageNavigation />
    </div>
  );
};

export default About;
